### ISSUE TITLE
POST-PUT Creation > Incorrect use of HTTP verbs

### ISSUE THREAD

**Issue by odrotbohm** [restalk/restalk-patterns#1]
> Context:
> If a client wants to create a resource whose URI it does not know, it has to use a **PUT** request.

Shouldn't that be `POST`?

> Problem:
> …
> This is not a problem if the request was using an idempotent HTTP verb like **PUT, PUT or, PUT**. However, if a client uses a _PUT_ request because it wants to create a resource whose URI will be determined by the server, how can the creation be repeated without resulting in multiple resources being created?

I guess the first enumeration is supposed to state `GET`, `PUT`, `DELETE`, and the final mention is again referring to the non-idempotency of a `POST` request.

**Comment by saivlis** [comment]
Thanks a lot, I fixed it.

**Comment by odrotbohm** [comment]
Line 86 still erroneously mentions PUT as the method to create a resource with the server in charge of defining the URI of the resource to be created.

**Comment by saivlis** [comment]
I already fixed some more copy & paste errors in that pattern description.

**Comment by odrotbohm** [comment]
👍🙃
