### ISSUE TITLE
Have you considered a more contribution-friendly source format?

### ISSUE THREAD

**Issue by odrotbohm** [restalk/restalk-patterns#3]
I can see the appeal of keeping the content in HTML directly as it's easy to distribute in the web that way. However, as the content is primarily text based, it might attract more collaborators if the sources were in a format that's better suited for authoring (e.g. Asciidoc or Markdown) as you then don't have to deal with indentation of tags, repetition of the layout into every single file etc.

I wouldn't mind helping to transfer the content and setting up Jekyll. The latter seems to have worked pretty well for other efforts (e.g. http://roca-style.org, http://scs-architecture.org).

**Comment by saivlis** [comment]
The HTML is actually generated by some scripts that are located in the master but that is only a temporary solution. The setup of this page had to be done quickly and I reused something existing.

**Comment by saivlis** [comment]
I finally found some time. So I hope that the new format makes contributions much more easily. Thank you for the suggestion.
